# Configure Cloudflare Worker

name = 'sitio-hernandezz-net'
compatibility_date = '2025-09-07'

[build]
command = './build.sh'

[assets]
directory = './public'
not_found_handling = '404-page'

[[routes]]
pattern = "hernandezz.net"
custom_domain = true